# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'ImagePickerDemoApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ImagePickerDemoApp
    pod 'ImagePicker'
    pod 'Gallery'
    pod 'Lightbox'
    pod 'Firebase/Core'
    pod 'Firebase/Storage'
    pod 'Firebase/Database'
    pod 'SDWebImage'
    pod 'SVProgressHUD'
end
